#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

mkdir -p build/obj build/generated/shaders

SHADER_SRC="resources/shaders/gradient.comp"
SHADER_SPV="build/generated/shaders/gradient.comp.spv"
SHADER_HDR="build/generated/shaders/gradient_comp_spv.h"

OS_NAME="$(uname -s)"
if [[ "$OS_NAME" == "Darwin" ]]; then
  PLATFORM_SRC="src/macos_platform.m"
  PLATFORM_OBJ="build/obj/macos_platform.o"
  OUTPUT_BIN="build/greatbadbeyond"
  VULKAN_LIB="-lvulkan"
  PLATFORM_LINK=("-framework" "AppKit" "-framework" "QuartzCore")
  LIB_DIRS=("-L/usr/local/lib" "-L/opt/homebrew/lib")
  RPATHS=("-Wl,-rpath,/usr/local/lib" "-Wl,-rpath,/opt/homebrew/lib")

  if [[ -n "${VULKAN_SDK:-}" ]]; then
    GLSLC="$VULKAN_SDK/bin/glslc"
    VULKAN_INC="-I$VULKAN_SDK/include"
    LIB_DIRS=("-L$VULKAN_SDK/lib" "${LIB_DIRS[@]}")
    RPATHS=("-Wl,-rpath,$VULKAN_SDK/lib" "${RPATHS[@]}")
  else
    GLSLC="glslc"
    VULKAN_INC=""
  fi
elif [[ "$OS_NAME" == MINGW* || "$OS_NAME" == MSYS* || "$OS_NAME" == CYGWIN* ]]; then
  PLATFORM_SRC="src/windows_platform.c"
  PLATFORM_OBJ="build/obj/windows_platform.o"
  OUTPUT_BIN="build/greatbadbeyond.exe"
  VULKAN_LIB="-lvulkan-1"
  PLATFORM_LINK=("-luser32")
  LIB_DIRS=()
  RPATHS=()

  if [[ -n "${VULKAN_SDK:-}" ]]; then
    GLSLC="$VULKAN_SDK/Bin/glslc.exe"
    VULKAN_INC="-I$VULKAN_SDK/Include"
    LIB_DIRS=("-L$VULKAN_SDK/Lib")
  else
    GLSLC="glslc"
    VULKAN_INC=""
  fi
else
  echo "Unsupported host platform: $OS_NAME" >&2
  exit 1
fi

if [[ ! -f src/main.c || ! -f "$PLATFORM_SRC" ]]; then
  echo "Run from repo root" >&2
  exit 1
fi

echo "$GLSLC $SHADER_SRC -o $SHADER_SPV"
"$GLSLC" "$SHADER_SRC" -o "$SHADER_SPV"

SHADER_BYTES="$(wc -c < "$SHADER_SPV" | tr -d '[:space:]')"
if [[ "$SHADER_BYTES" == "0" ]] || (( SHADER_BYTES % 4 != 0 )); then
  echo "Invalid SPIR-V byte size: $SHADER_BYTES" >&2
  exit 1
fi

{
  echo "// Generated by build.sh. Do not edit."
  echo "#pragma once"
  echo
  echo "#include <stddef.h>"
  echo "#include <stdint.h>"
  echo
  echo "static const uint32_t kGradientCompSpv[] = {"
  od -An -v -t x4 "$SHADER_SPV" | awk '
  {
    for (i = 1; i <= NF; ++i) {
      printf "0x%su,", $i;
      ++count;
      if ((count % 8) == 0) {
        printf "\n";
      } else {
        printf " ";
      }
    }
  }
  END {
    if ((count % 8) != 0) {
      printf "\n";
    }
  }
  '
  echo "};"
  echo "static const size_t kGradientCompSpv_size = $SHADER_BYTES;"
} > "$SHADER_HDR"

MAIN_CMD="clang -std=c11 -g -Wall -Wextra -Wpedantic -Ibuild/generated/shaders"
if [[ -n "$VULKAN_INC" ]]; then
  MAIN_CMD+=" $VULKAN_INC"
fi
MAIN_CMD+=" -c src/main.c -o build/obj/main.o"

PLATFORM_CMD="clang -std=c11 -g -Wall -Wextra -Wpedantic"
if [[ -n "$VULKAN_INC" ]]; then
  PLATFORM_CMD+=" $VULKAN_INC"
fi
PLATFORM_CMD+=" -c $PLATFORM_SRC -o $PLATFORM_OBJ"

cat > compile_commands.json <<EOF_JSON
[
  {
    "directory": "$ROOT_DIR",
    "file": "src/main.c",
    "command": "$MAIN_CMD"
  },
  {
    "directory": "$ROOT_DIR",
    "file": "$PLATFORM_SRC",
    "command": "$PLATFORM_CMD"
  }
]
EOF_JSON

echo "$MAIN_CMD"
clang -std=c11 -g -Wall -Wextra -Wpedantic -Ibuild/generated/shaders ${VULKAN_INC:+$VULKAN_INC} -c src/main.c -o build/obj/main.o

echo "$PLATFORM_CMD"
clang -std=c11 -g -Wall -Wextra -Wpedantic ${VULKAN_INC:+$VULKAN_INC} -c "$PLATFORM_SRC" -o "$PLATFORM_OBJ"

echo "clang build/obj/main.o $PLATFORM_OBJ ${LIB_DIRS[*]} ${RPATHS[*]} $VULKAN_LIB ${PLATFORM_LINK[*]} -o $OUTPUT_BIN"
clang build/obj/main.o "$PLATFORM_OBJ" "${LIB_DIRS[@]}" "${RPATHS[@]}" "$VULKAN_LIB" "${PLATFORM_LINK[@]}" -o "$OUTPUT_BIN"

echo "built $OUTPUT_BIN"
