#version 460
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(set = 0, binding = 0, rgba8) uniform writeonly image2D img;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size  = imageSize(img);
    if (any(greaterThanEqual(coord, size))) { return; }

    vec2 uv = (vec2(coord) + vec2(0.5)) / vec2(size);
    imageStore(img, coord, vec4(uv, 0.0, 1.0));
}
