if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

if(NOT DEFINED SYMBOL_NAME)
    message(FATAL_ERROR "SYMBOL_NAME is required")
endif()

if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "Input SPIR-V file not found: ${INPUT_FILE}")
endif()

file(READ "${INPUT_FILE}" shaderHex HEX)
string(LENGTH "${shaderHex}" shaderHexLength)

if(shaderHexLength EQUAL 0)
    message(FATAL_ERROR "Input SPIR-V file is empty: ${INPUT_FILE}")
endif()

math(EXPR shaderByteCount "${shaderHexLength}/2")
math(EXPR lastByteIndex "${shaderByteCount} - 1")

set(outputText "// Generated by cmake/embed_spv.cmake. Do not edit.\n")
string(APPEND outputText "#pragma once\n\n")
string(APPEND outputText "#include <cstddef>\n")
string(APPEND outputText "#include <cstdint>\n\n")
string(APPEND outputText "alignas(4) static constexpr std::uint8_t ${SYMBOL_NAME}[] = {\n")

set(bytesOnLine 0)
foreach(byteIndex RANGE 0 ${lastByteIndex})
    math(EXPR hexIndex "${byteIndex}*2")
    string(SUBSTRING "${shaderHex}" ${hexIndex} 2 byteHex)

    string(APPEND outputText "0x${byteHex}")

    if(NOT byteIndex EQUAL lastByteIndex)
        string(APPEND outputText ", ")
    endif()

    math(EXPR bytesOnLine "${bytesOnLine} + 1")
    if(bytesOnLine EQUAL 12)
        string(APPEND outputText "\n")
        set(bytesOnLine 0)
    endif()
endforeach()

if(NOT bytesOnLine EQUAL 0)
    string(APPEND outputText "\n")
endif()

string(APPEND outputText "};\n")
string(APPEND outputText "static constexpr std::size_t ${SYMBOL_NAME}_size = sizeof(${SYMBOL_NAME});\n")

file(WRITE "${OUTPUT_FILE}" "${outputText}")
